---
title: Martin Charlwood
description: Welcome to mec.me.uk, the subdomain of the apex domain me.uk! Built with
  ❤️
baseurl: ''
url: http://mec.me.uk
github_username: mec337
theme: minima
plugins:
- jekyll-feed
static_files:
- assets
build_count: 5
